"""added packaging_charge col in orders table

Revision ID: 18812fcfcf5e
Revises: f126ee01b728
Create Date: 2025-12-09 08:01:22.301638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18812fcfcf5e'
down_revision: Union[str, Sequence[str], None] = 'f126ee01b728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('packaging_charge', sa.DECIMAL(precision=10, scale=2), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'packaging_charge')
    # ### end Alembic commands ###
