"""added refund_mode column 

Revision ID: 05f293b7e120
Revises: 719b13a2500f
Create Date: 2025-09-17 05:16:52.168815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05f293b7e120'
down_revision: Union[str, Sequence[str], None] = '719b13a2500f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'pos_extra_quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.add_column('returns', sa.Column('refund_mode', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('returns', 'refund_mode')
    op.alter_column('order_items', 'pos_extra_quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    # ### end Alembic commands ###
