"""add biller_id and biller_name

Revision ID: 6aa80d8388ea
Revises: 05f293b7e120
Create Date: 2025-09-18 06:16:16.277058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aa80d8388ea'
down_revision: Union[str, Sequence[str], None] = '05f293b7e120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('biller_id', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('biller_name', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'biller_name')
    op.drop_column('orders', 'biller_id')
    # ### end Alembic commands ###
