"""remove_version_from_orders_rename_app_version_to_version_in_metadata

Revision ID: d3c38e1d1b57
Revises: 18812fcfcf5e
Create Date: 2025-12-22 10:54:53.810234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3c38e1d1b57'
down_revision: Union[str, Sequence[str], None] = '18812fcfcf5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_metadata', sa.Column('version', sa.String(length=64), nullable=True))
    op.drop_column('order_metadata', 'app_version')
    op.drop_column('orders', 'version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('version', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('order_metadata', sa.Column('app_version', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('order_metadata', 'version')
    # ### end Alembic commands ###
