"""add orde_metada

Revision ID: c388a7b487ec
Revises: 6aa80d8388ea
Create Date: 2025-09-19 09:35:29.084622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c388a7b487ec'
down_revision: Union[str, Sequence[str], None] = '6aa80d8388ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device', sa.String(length=128), nullable=True),
    sa.Column('platform', sa.String(length=128), nullable=True),
    sa.Column('app_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_metadata_order_id', 'order_metadata', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_metadata_id'), 'order_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_order_metadata_order_id'), 'order_metadata', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_metadata_order_id'), table_name='order_metadata')
    op.drop_index(op.f('ix_order_metadata_id'), table_name='order_metadata')
    op.drop_index('idx_order_metadata_order_id', table_name='order_metadata')
    op.drop_table('order_metadata')
    # ### end Alembic commands ###
