"""added return_status column

Revision ID: b434ccff18f7
Revises: c388a7b487ec
Create Date: 2025-09-19 15:44:07.415619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b434ccff18f7'
down_revision: Union[str, Sequence[str], None] = 'c388a7b487ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('return_items', sa.Column('return_status', sa.Integer(), server_default='40', nullable=False))
    op.add_column('returns', sa.Column('return_status', sa.Integer(), server_default='40', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('returns', 'return_status')
    op.drop_column('return_items', 'return_status')
    # ### end Alembic commands ###
