"""changed to 3 decimals

Revision ID: e8abe1eb3c82
Revises: b434ccff18f7
Create Date: 2025-09-20 10:25:09.286705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8abe1eb3c82'
down_revision: Union[str, Sequence[str], None] = 'b434ccff18f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DECIMAL(precision=10, scale=3),
               existing_nullable=False)
    op.alter_column('order_items', 'fulfilled_quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DECIMAL(precision=10, scale=3),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('order_items', 'unfulfilled_quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DECIMAL(precision=10, scale=3),
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('order_items', 'delivered_quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DECIMAL(precision=10, scale=3),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('order_items', 'cancelled_quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DECIMAL(precision=10, scale=3),
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('order_items', 'refunded_quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DECIMAL(precision=10, scale=3),
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('order_items', 'pos_extra_quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DECIMAL(precision=10, scale=3),
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'pos_extra_quantity',
               existing_type=sa.DECIMAL(precision=10, scale=3),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('order_items', 'refunded_quantity',
               existing_type=sa.DECIMAL(precision=10, scale=3),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('order_items', 'cancelled_quantity',
               existing_type=sa.DECIMAL(precision=10, scale=3),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('order_items', 'delivered_quantity',
               existing_type=sa.DECIMAL(precision=10, scale=3),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('order_items', 'unfulfilled_quantity',
               existing_type=sa.DECIMAL(precision=10, scale=3),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('order_items', 'fulfilled_quantity',
               existing_type=sa.DECIMAL(precision=10, scale=3),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('order_items', 'quantity',
               existing_type=sa.DECIMAL(precision=10, scale=3),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
