"""changed quantity_returned and accepted_quantity to decimal

Revision ID: de82509bd250
Revises: e8abe1eb3c82
Create Date: 2025-09-20 13:25:24.679064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de82509bd250'
down_revision: Union[str, Sequence[str], None] = 'e8abe1eb3c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('return_items', 'quantity_returned',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=3),
               existing_nullable=False)
    op.alter_column('return_items', 'accepted_quantity',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=3),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('return_items', 'accepted_quantity',
               existing_type=sa.DECIMAL(precision=10, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('return_items', 'quantity_returned',
               existing_type=sa.DECIMAL(precision=10, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
