"""added remarks column

Revision ID: 7e39b33e59b3
Revises: de82509bd250
Create Date: 2025-10-01 06:17:08.844276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e39b33e59b3'
down_revision: Union[str, Sequence[str], None] = 'de82509bd250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('remarks', sa.String(length=255), server_default=sa.text("''"), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'remarks')
    # ### end Alembic commands ###
