"""added remarks column in order_items table

Revision ID: 378bb35f417d
Revises: 7e39b33e59b3
Create Date: 2025-10-01 07:39:12.850359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '378bb35f417d'
down_revision: Union[str, Sequence[str], None] = '7e39b33e59b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('remarks', sa.String(length=255), server_default=sa.text("''"), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'remarks')
    # ### end Alembic commands ###
