"""added promotional columns

Revision ID: 56123f679662
Revises: 378bb35f417d
Create Date: 2025-10-05 13:27:22.408588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56123f679662'
down_revision: Union[str, Sequence[str], None] = '378bb35f417d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('promotion_code', sa.String(length=50), server_default=sa.text("''"), nullable=True))
    op.add_column('orders', sa.Column('promotion_type', sa.String(length=10), server_default=sa.text("''"), nullable=True))
    op.add_column('orders', sa.Column('promotion_discount', sa.DECIMAL(precision=10, scale=2), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'promotion_discount')
    op.drop_column('orders', 'promotion_type')
    op.drop_column('orders', 'promotion_code')
    # ### end Alembic commands ###
