"""added hsn_code column

Revision ID: 323c68ff5f08
Revises: 75b425cd2ba9
Create Date: 2025-10-15 12:03:18.056665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '323c68ff5f08'
down_revision: Union[str, Sequence[str], None] = '75b425cd2ba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('hsn_code', sa.String(length=10), server_default=sa.text("''"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'hsn_code')
    # ### end Alembic commands ###
