"""added new columns

Revision ID: 633153a260f3
Revises: 323c68ff5f08
Create Date: 2025-10-17 07:21:08.048468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '633153a260f3'
down_revision: Union[str, Sequence[str], None] = '323c68ff5f08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('category', sa.String(length=255), server_default=sa.text("''"), nullable=False))
    op.add_column('order_items', sa.Column('sub_category', sa.String(length=255), server_default=sa.text("''"), nullable=False))
    op.add_column('order_items', sa.Column('sub_sub_category', sa.String(length=255), server_default=sa.text("''"), nullable=False))
    op.add_column('order_items', sa.Column('brand_name', sa.String(length=255), server_default=sa.text("''"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'brand_name')
    op.drop_column('order_items', 'sub_sub_category')
    op.drop_column('order_items', 'sub_category')
    op.drop_column('order_items', 'category')
    # ### end Alembic commands ###
