"""added typesense id field in items table

Revision ID: 662753723bd4
Revises: 633153a260f3
Create Date: 2025-10-18 10:53:54.154870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '662753723bd4'
down_revision: Union[str, Sequence[str], None] = '633153a260f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('typesense_id', sa.String(length=100), server_default=sa.text("''"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'typesense_id')
    # ### end Alembic commands ###
