"""added ondc columns

Revision ID: f126ee01b728
Revises: 3a5f17070857
Create Date: 2025-12-09 05:17:01.134795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f126ee01b728'
down_revision: Union[str, Sequence[str], None] = '3a5f17070857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('domain_name', sa.String(length=32), server_default=sa.text("''"), nullable=False))
    op.add_column('order_items', sa.Column('provider_id', sa.String(length=128), server_default=sa.text("''"), nullable=False))
    op.add_column('order_items', sa.Column('location_id', sa.String(length=128), server_default=sa.text("''"), nullable=False))
    op.add_column('orders', sa.Column('domain_name', sa.String(length=32), server_default=sa.text("''"), nullable=False))
    op.add_column('orders', sa.Column('provider_id', sa.String(length=128), server_default=sa.text("''"), nullable=False))
    op.add_column('orders', sa.Column('location_id', sa.String(length=128), server_default=sa.text("''"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'location_id')
    op.drop_column('orders', 'provider_id')
    op.drop_column('orders', 'domain_name')
    op.drop_column('order_items', 'location_id')
    op.drop_column('order_items', 'provider_id')
    op.drop_column('order_items', 'domain_name')
    # ### end Alembic commands ###
