"""addeding_selling_price

Revision ID: cfb0e8236508
Revises: 662753723bd4
Create Date: 2025-10-26 14:21:35.449818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfb0e8236508'
down_revision: Union[str, Sequence[str], None] = '662753723bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellingpricemapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('selling_price_key', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_selling_price_mapping_created', 'sellingpricemapping', ['created_at'], unique=False)
    op.create_index('idx_selling_price_mapping_key_type', 'sellingpricemapping', ['selling_price_key', 'user_type'], unique=False)
    op.create_index('idx_selling_price_mapping_status', 'sellingpricemapping', ['status'], unique=False)
    op.create_index(op.f('ix_sellingpricemapping_id'), 'sellingpricemapping', ['id'], unique=False)
    op.create_index(op.f('ix_sellingpricemapping_selling_price_key'), 'sellingpricemapping', ['selling_price_key'], unique=False)
    op.create_index(op.f('ix_sellingpricemapping_user_type'), 'sellingpricemapping', ['user_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sellingpricemapping_user_type'), table_name='sellingpricemapping')
    op.drop_index(op.f('ix_sellingpricemapping_selling_price_key'), table_name='sellingpricemapping')
    op.drop_index(op.f('ix_sellingpricemapping_id'), table_name='sellingpricemapping')
    op.drop_index('idx_selling_price_mapping_status', table_name='sellingpricemapping')
    op.drop_index('idx_selling_price_mapping_key_type', table_name='sellingpricemapping')
    op.drop_index('idx_selling_price_mapping_created', table_name='sellingpricemapping')
    op.drop_table('sellingpricemapping')
    # ### end Alembic commands ###
