"""added user type col in orders

Revision ID: f1db4a620e15
Revises: cfb0e8236508
Create Date: 2025-10-26 15:25:04.863321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1db4a620e15'
down_revision: Union[str, Sequence[str], None] = 'cfb0e8236508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_type', sa.String(length=100), server_default='customer', nullable=False))
    op.create_index(op.f('ix_orders_user_type'), 'orders', ['user_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_user_type'), table_name='orders')
    op.drop_column('orders', 'user_type')
    # ### end Alembic commands ###
