"""added salereturn_id column in returns table

Revision ID: 9a8fff61c0f1
Revises: f1db4a620e15
Create Date: 2025-10-28 04:33:21.772997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a8fff61c0f1'
down_revision: Union[str, Sequence[str], None] = 'f1db4a620e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('returns', sa.Column('sale_return_id', sa.String(length=50), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('returns', 'sale_return_id')
    # ### end Alembic commands ###
