"""added updated_by in orders and order_items tables

Revision ID: 40b3075f88a8
Revises: 9a8fff61c0f1
Create Date: 2025-10-29 15:33:55.939326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b3075f88a8'
down_revision: Union[str, Sequence[str], None] = '9a8fff61c0f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('updated_by', sa.String(length=255), server_default=sa.text("''"), nullable=False))
    op.add_column('orders', sa.Column('updated_by', sa.String(length=255), server_default=sa.text("''"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'updated_by')
    op.drop_column('order_items', 'updated_by')
    # ### end Alembic commands ###
