"""create facility payment gateway table

Revision ID: 8bccaacbd25d
Revises: 40b3075f88a8
Create Date: 2025-10-31 06:46:51.774477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bccaacbd25d'
down_revision: Union[str, Sequence[str], None] = '40b3075f88a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility_payment_gateways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_name', sa.String(length=100), nullable=False),
    sa.Column('payment_gateway', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_facility_gateway_active', 'facility_payment_gateways', ['facility_name', 'payment_gateway', 'is_active'], unique=False)
    op.create_index('idx_facility_payment_gateway', 'facility_payment_gateways', ['facility_name', 'payment_gateway'], unique=True)
    op.create_index(op.f('ix_facility_payment_gateways_id'), 'facility_payment_gateways', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facility_payment_gateways_id'), table_name='facility_payment_gateways')
    op.drop_index('idx_facility_payment_gateway', table_name='facility_payment_gateways')
    op.drop_index('idx_facility_gateway_active', table_name='facility_payment_gateways')
    op.drop_table('facility_payment_gateways')
    # ### end Alembic commands ###
