"""added terminals

Revision ID: 2202a5f314b7
Revises: 8bccaacbd25d
Create Date: 2025-11-06 07:56:10.260424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2202a5f314b7'
down_revision: Union[str, Sequence[str], None] = '8bccaacbd25d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility_terminals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_code', sa.String(length=100), nullable=False),
    sa.Column('terminal_id', sa.String(length=50), nullable=False),
    sa.Column('terminal_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_facility_active', 'facility_terminals', ['facility_code', 'is_active'], unique=False)
    op.create_index('idx_facility_terminal', 'facility_terminals', ['facility_code', 'terminal_id'], unique=True)
    op.create_index(op.f('ix_facility_terminals_facility_code'), 'facility_terminals', ['facility_code'], unique=False)
    op.create_index(op.f('ix_facility_terminals_id'), 'facility_terminals', ['id'], unique=False)
    op.create_index(op.f('ix_facility_terminals_is_active'), 'facility_terminals', ['is_active'], unique=False)
    op.create_index(op.f('ix_facility_terminals_terminal_id'), 'facility_terminals', ['terminal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facility_terminals_terminal_id'), table_name='facility_terminals')
    op.drop_index(op.f('ix_facility_terminals_is_active'), table_name='facility_terminals')
    op.drop_index(op.f('ix_facility_terminals_id'), table_name='facility_terminals')
    op.drop_index(op.f('ix_facility_terminals_facility_code'), table_name='facility_terminals')
    op.drop_index('idx_facility_terminal', table_name='facility_terminals')
    op.drop_index('idx_facility_active', table_name='facility_terminals')
    op.drop_table('facility_terminals')
    # ### end Alembic commands ###
