"""added version column

Revision ID: 36ae87d62a9a
Revises: 2202a5f314b7
Create Date: 2025-11-07 20:55:46.185714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36ae87d62a9a'
down_revision: Union[str, Sequence[str], None] = '2202a5f314b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('version', sa.String(length=50), server_default=sa.text("''"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'version')
    # ### end Alembic commands ###
