"""added terminal id

Revision ID: e7dab8e89522
Revises: 36ae87d62a9a
Create Date: 2025-11-08 11:40:48.103419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7dab8e89522'
down_revision: Union[str, Sequence[str], None] = '36ae87d62a9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_details', sa.Column('terminal_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_payment_details_terminal_id'), 'payment_details', ['terminal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_details_terminal_id'), table_name='payment_details')
    op.drop_column('payment_details', 'terminal_id')
    # ### end Alembic commands ###
