"""create static_otps table

Revision ID: 8d1ef6859a3b
Revises: 36ae87d62a9a
Create Date: 2025-11-08 06:16:00.449491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d1ef6859a3b'
down_revision: Union[str, Sequence[str], None] = 'e7dab8e89522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('static_otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('otp', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_static_otps_id'), 'static_otps', ['id'], unique=False)
    op.create_index(op.f('ix_static_otps_phone_number'), 'static_otps', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_static_otps_phone_number'), table_name='static_otps')
    op.drop_index(op.f('ix_static_otps_id'), table_name='static_otps')
    op.drop_table('static_otps')
    # ### end Alembic commands ###
