"""added cod amount column in order items table

Revision ID: 7be2a046b655
Revises: 8d1ef6859a3b
Create Date: 2025-11-11 16:17:05.510129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7be2a046b655'
down_revision: Union[str, Sequence[str], None] = '8d1ef6859a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('cod_amount', sa.DECIMAL(precision=10, scale=2), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'cod_amount')
    # ### end Alembic commands ###
