"""added referral_id and marketplace column

Revision ID: 21a1a054a665
Revises: 7be2a046b655
Create Date: 2025-11-13 07:16:36.457035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21a1a054a665'
down_revision: Union[str, Sequence[str], None] = '7be2a046b655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('marketplace', sa.String(length=32), server_default='ROZANA', nullable=False))
    op.add_column('order_items', sa.Column('referral_id', sa.String(length=32), server_default=sa.text("''"), nullable=False))
    op.add_column('orders', sa.Column('marketplace', sa.String(length=32), server_default='ROZANA', nullable=False))
    op.add_column('orders', sa.Column('referral_id', sa.String(length=32), server_default=sa.text("''"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'referral_id')
    op.drop_column('orders', 'marketplace')
    op.drop_column('order_items', 'referral_id')
    op.drop_column('order_items', 'marketplace')
    # ### end Alembic commands ###
