"""added merchant_id and merchant_key column in facility_terminals table

Revision ID: 8e8e25a5462d
Revises: 21a1a054a665
Create Date: 2025-11-18 09:45:02.620477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e8e25a5462d'
down_revision: Union[str, Sequence[str], None] = '21a1a054a665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facility_terminals', sa.Column('merchant_id', sa.String(length=100), nullable=True))
    op.add_column('facility_terminals', sa.Column('merchant_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facility_terminals', 'merchant_key')
    op.drop_column('facility_terminals', 'merchant_id')
    # ### end Alembic commands ###
