"""added wh_cancel reasons

Revision ID: c7b504673eee
Revises: 8e8e25a5462d
Create Date: 2025-11-19 05:07:32.900652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7b504673eee'
down_revision: Union[str, Sequence[str], None] = '8e8e25a5462d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('cancel_reason', sa.String(length=100), server_default=sa.text("''"), nullable=False))
    op.add_column('orders', sa.Column('cancel_remarks', sa.String(length=255), server_default=sa.text("''"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'cancel_remarks')
    op.drop_column('orders', 'cancel_reason')
    # ### end Alembic commands ###
