"""added longitude and latitude col in metadata

Revision ID: 1599044aec7b
Revises: c7b504673eee
Create Date: 2025-11-26 06:53:49.284099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1599044aec7b'
down_revision: Union[str, Sequence[str], None] = 'c7b504673eee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_metadata', sa.Column('longitude', sa.DECIMAL(precision=10, scale=7), server_default='0.00', nullable=False))
    op.add_column('order_metadata', sa.Column('latitude', sa.DECIMAL(precision=10, scale=7), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_metadata', 'latitude')
    op.drop_column('order_metadata', 'longitude')
    # ### end Alembic commands ###
