"""added parent_order_id column in orders table

Revision ID: c32af68cedae
Revises: 1599044aec7b
Create Date: 2025-11-29 07:12:27.774075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c32af68cedae'
down_revision: Union[str, Sequence[str], None] = '1599044aec7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('parent_order_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'parent_order_id')
    # ### end Alembic commands ###
