"""added remarks column in payment details table

Revision ID: c2c25a88499f
Revises: c32af68cedae
Create Date: 2025-12-02 11:20:19.903685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2c25a88499f'
down_revision: Union[str, Sequence[str], None] = 'c32af68cedae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_details', sa.Column('remarks', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_details', 'remarks')
    # ### end Alembic commands ###
