"""add facility configuration table

Revision ID: 3a5f17070857
Revises: c2c25a88499f
Create Date: 2025-12-06 16:27:35.391562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a5f17070857'
down_revision: Union[str, Sequence[str], None] = 'c2c25a88499f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_name', sa.String(length=255), nullable=False),
    sa.Column('config_key', sa.String(length=255), nullable=False),
    sa.Column('config_value', sa.String(length=1000), nullable=False),
    sa.Column('config_value_type', sa.String(length=50), nullable=False),
    sa.Column('config_type', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_facility_config', 'facility_configurations', ['facility_name', 'config_key'], unique=True)
    op.create_index(op.f('ix_facility_configurations_config_key'), 'facility_configurations', ['config_key'], unique=False)
    op.create_index(op.f('ix_facility_configurations_facility_name'), 'facility_configurations', ['facility_name'], unique=False)
    op.create_index(op.f('ix_facility_configurations_id'), 'facility_configurations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facility_configurations_id'), table_name='facility_configurations')
    op.drop_index(op.f('ix_facility_configurations_facility_name'), table_name='facility_configurations')
    op.drop_index(op.f('ix_facility_configurations_config_key'), table_name='facility_configurations')
    op.drop_index('idx_facility_config', table_name='facility_configurations')
    op.drop_table('facility_configurations')
    # ### end Alembic commands ###
